name: Steam Freebie Bot

on:
  schedule:
    - cron: '0 * * * *'  # Runs every single hour
  workflow_dispatch:      # Allows manual trigger button

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository Code
      uses: actions/checkout@v4

    - name: Set Up Python Environments
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install System Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Storage Bot Script
      env:
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: python main.py
